// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteDocument(arg1:number):Promise<void>;

export function ExportPDF(arg1:number):Promise<string>;

export function GetDocument(arg1:number):Promise<model.Document>;

export function GetSettings():Promise<model.Settings>;

export function ListDocuments():Promise<Array<model.DocumentSummary>>;

export function ListTemplates():Promise<Array<model.Template>>;

export function NewDocumentDraft(arg1:number):Promise<model.Document>;

export function SaveDocument(arg1:model.Document):Promise<model.Document>;

export function SaveSettings(arg1:model.Settings):Promise<void>;

export function SaveTemplates(arg1:Array<model.Template>):Promise<void>;
